id: outdoor_pool
description: "Outdoor Pool, Adventure Pool, Thermal Bath"
symbol: Swimming Area
require_distinct_name: true
defaults:
  max_km: 2.0
  sample_km: 15.0
  batch_size: 6
  retries: 2
tags:
  - key: leisure
    value: swimming_pool
    and_not:
      - key: access
        value: private
      - key: access
        value: "no"
  - key: leisure
    value: water_park
  - key: amenity
    value: public_bath
terms: {}
